Bookstore/Bookstore/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from book_details import views
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', include('book_browsing.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^products/', include('products.urls', namespace='products')),
    url('profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^author/(\d+)/$', views.bookAuthorsView.as_view(), name='book_author'),
    path('book/<int:pk>', views.bookDetailsView.as_view(), name='book'),
    path('author/<int:pk>', views.bookAuthorsView.as_view(), name='book-author'),
    url(r'^book/(?P<pk>\d+)/$', views.bookDetailsView.as_view(), name='book_details')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bookstore/home/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage_view, name='the_homepage_base'),
    url(r'^home/$', views.homepage_view, name = 'the_homepage'),
]

Bookstore/shopping_cart/urls.py
from django import views
from django.conf.urls import url
from django.urls import path

from .views import (
    add_to_cart,
    add_to_cart_from_saved,
    add_to_cart_from_detail,
    increase_item_quantity,
    decrease_item_quantity,
    add_to_saved,
    add_to_saved_from_cart,
    delete_from_cart,
    delete_from_saved,
    order_details,
    checkout,
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^add-to-cart-from-saved/(?P<item_id>[-\w]+)/$', add_to_cart_from_saved, name="add_to_cart_from_saved"),
    url(r'^add-to-cart-from-detail/(?P<item_id>[-\w]+)$', add_to_cart_from_detail, name="add_to_cart_from_detail"),
    url(r'^increase_item_quantity/(?P<item_id>[-\w]+)/$', increase_item_quantity, name="increase_item_quantity"),
    url(r'^decrease_item_quantity/(?P<item_id>[-\w]+)/$', decrease_item_quantity, name="decrease_item_quantity"),
    url(r'^add-to-saved/(?P<item_id>[-\w]+)/$', add_to_saved, name="add_to_saved"),
    url(r'^add-to-saved_from_cart/(?P<item_id>[-\w]+)/$', add_to_saved_from_cart, name="add_to_saved_from_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^item/delete_saved/(?P<item_id>[-\w]+)/$', delete_from_saved, name='delete_item_from_saved'),
    url(r'^checkout/$', checkout, name='checkout'),
]

Bookstore/home/models.py
from django.db import models
from django.urls import reverse

Bookstore/home/views.py
from django.shortcuts import render, get_object_or_404

def homepage_view(request):
    return render(request, 'home/base.html')

Bookstore/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Bookbuy </title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">G19 Bookstore </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarsExampleDefault">
            <ul class="navbar-nav m-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'homepage:the_homepage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Profile <span class="sr-only">(current)</span></a>
                </li>
            </ul>

            <form class="form-inline my-2 my-lg-0">   
                <a class="btn btn-success btn-sm ml-3" href="{%  url 'shopping_cart:order_summary' %}">
                    <i class="fa fa-shopping-cart"></i> Cart
                    <span class="badge badge-light"></span>
                </a>
            </form>
        </div>
    </div>
</nav>
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">TEMPLATE FOR HOMEPAGE</h1>
     </div>
</section>

<div class="row">
{% for object in object_list %}
    <div class="col-sm-3">
        <p>{{object.name}}</p>
        <p>Price: ${{ object.price }}</p>
        <a href="{% url 'shopping_cart:add_to_cart' object.id %}" class="btn btn-dark">Add to Cart</a>
    </div>
{% endfor %}
</div>

<!-- Footer -->
<footer class="text-dark">
    <div class="container">
        <div class="row">
            </div>
            <div class="col-12 copyright mt-3">
                <p class="float-left">
                    <a href="#">Back to top</a>
                </p>
            </div>
        </div>
    </div>
</footer>
</body>
</html>