Bookstore/Bookstore/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from book_details import views
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', include('book_browsing.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^products/', include('products.urls', namespace='products')),
    url('profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^author/(\d+)/$', views.bookAuthorsView.as_view(), name='book_author'),
    path('book/<int:pk>', views.bookDetailsView.as_view(), name='book'),
    path('author/<int:pk>', views.bookAuthorsView.as_view(), name='book-author'),
    url(r'^book/(?P<pk>\d+)/$', views.bookDetailsView.as_view(), name='book_details')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bookstore/book_browsing/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'book_browsing'

urlpatterns = [
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('book/', views.book, name='book'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('order/', views.order, name='order'),
    path('new-book/', views.newBook, name='new-book'),
    path('search/', views.search, name='search'),
    path('fantasy/', views.fantasy, name='fantasy'),
    path('romance/', views.romance, name='romance'),
    path('fiction/', views.fiction, name='fiction'),
    path('history/', views.history, name='history'),
    path('thriller/', views.thriller, name='thriller'),
    path('new-release/', views.newRelease, name='new-release'),
    path('top-sellers/', views.topSeller, name='top-sellers'),
    path('filter-data/', views.filterData, name='filter-data'),
    path('filter-released-data/', views.filterReleasedData, name='filter-released-data'),
    path('get-book-details/', views.getBookDetailsById, name='get-book-details'),
    path('ajax-submit/', views.ajaxSubmit, name='ajax-submit')
]

Bookstore/home/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage_view, name='the_homepage_base'),
    url(r'^home/$', views.homepage_view, name = 'the_homepage'),
]

Bookstore/products/urls.py
from django.conf.urls import url

from .views import product_list

app_name = 'products'

urlpatterns = [
    url(r'^', product_list, name='product-list')
]

Bookstore/shopping_cart/urls.py
from django import views
from django.conf.urls import url
from django.urls import path

from .views import (
    add_to_cart,
    add_to_cart_from_saved,
    add_to_cart_from_detail,
    increase_item_quantity,
    decrease_item_quantity,
    add_to_saved,
    add_to_saved_from_cart,
    delete_from_cart,
    delete_from_saved,
    order_details,
    checkout,
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^add-to-cart-from-saved/(?P<item_id>[-\w]+)/$', add_to_cart_from_saved, name="add_to_cart_from_saved"),
    url(r'^add-to-cart-from-detail/(?P<item_id>[-\w]+)$', add_to_cart_from_detail, name="add_to_cart_from_detail"),
    url(r'^increase_item_quantity/(?P<item_id>[-\w]+)/$', increase_item_quantity, name="increase_item_quantity"),
    url(r'^decrease_item_quantity/(?P<item_id>[-\w]+)/$', decrease_item_quantity, name="decrease_item_quantity"),
    url(r'^add-to-saved/(?P<item_id>[-\w]+)/$', add_to_saved, name="add_to_saved"),
    url(r'^add-to-saved_from_cart/(?P<item_id>[-\w]+)/$', add_to_saved_from_cart, name="add_to_saved_from_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^item/delete_saved/(?P<item_id>[-\w]+)/$', delete_from_saved, name='delete_item_from_saved'),
    url(r'^checkout/$', checkout, name='checkout'),
]

Bookstore/shopping_cart/models.py
from __future__ import unicode_literals

from django.db import models

from accounts.models import Profile
from products.models import books


class OrderItem(models.Model):
    book = models.OneToOneField(books, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)
    quantity = models.PositiveIntegerField(default=1)
    price_in_cart = models.DecimalField(max_digits=5, decimal_places=2)
    is_saved_for_later = models.BooleanField(default=False)

    def __str__(self):
        return self.book.name


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.price_in_cart for item in self.items.all()])

    def cart_item_count(self):
        return self.items.count()

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)


class SaveItem(models.Model):
    saved_book = models.OneToOneField(books, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)
    is_saved_for_later = models.BooleanField(default=True)

    def __str__(self):
        return self.saved_book.name


class Saved(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    is_saved_for_later = models.BooleanField(default=True)
    saved_items = models.ManyToManyField(SaveItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_saved_items(self):
        return self.saved_items.all()

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)


class Transaction(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    token = models.CharField(max_length=120)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

Bookstore/shopping_cart/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404

from accounts.models import Profile
from products.models import books

from shopping_cart.extras import generate_order_id,  generate_save_id, transact, generate_client_token
from shopping_cart.models import OrderItem, Order, Transaction, SaveItem, Saved

import datetime
import stripe

stripe.api_key = "sk_test_4PDwRmxMmJFYdUbQHGMJz3zn003JF5ugKA"


def get_user_pending_order(request):
    # get order for the correct user
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0

@login_required()
def increase_item_quantity(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)

    # filter books by id
    book = books.objects.filter(id=kwargs.get('item_id', "")).first()

    # create orderItem of the selected book
    order_item, status = OrderItem.objects.get_or_create(book=book)
    order_item.quantity = order_item.quantity + 1
    order_item.price_in_cart = order_item.book.price * order_item.quantity
    order_item.save()

    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()

    books_for_order = OrderItem.objects.all().order_by('-book')
    sbooks = SaveItem.objects.all()

    context = {'user_order': user_order, 'books_for_order': books_for_order, 'sbooks': sbooks}

    return render(request,'shopping_cart/order_summary.html', context)

@login_required()
def decrease_item_quantity(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)

    # filter books by id
    book = books.objects.filter(id=kwargs.get('item_id', "")).first()

    # create orderItem of the selected book
    order_item, status = OrderItem.objects.get_or_create(book=book)
    if order_item.quantity > 1:
        order_item.quantity = order_item.quantity - 1
        order_item.price_in_cart = order_item.book.price * order_item.quantity
        order_item.save()

    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()

    books_for_order = OrderItem.objects.all().order_by('-book')
    sbooks = SaveItem.objects.all()

    context = {'user_order': user_order, 'books_for_order': books_for_order, 'sbooks': sbooks}

    return render(request,'shopping_cart/order_summary.html', context)

@login_required()
def add_to_cart(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)

    # filter books by id
    book = books.objects.filter(id=kwargs.get('item_id', "")).first()

    # create orderItem of the selected book
    order_item, status = OrderItem.objects.get_or_create(book=book, price_in_cart=book.price)

    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()

    books_for_order = OrderItem.objects.all().order_by('-book')
    sbooks = SaveItem.objects.all()

    context = {'user_order': user_order, 'books_for_order': books_for_order, 'sbooks': sbooks}

    # show confirmation message and redirect back to the same page
    messages.info(request, "Item has been added to cart")
    return redirect(request.META['HTTP_REFERER'])

@login_required()
def add_to_cart_from_detail(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)

    # filter books by id
    book = books.objects.filter(id=kwargs.get('item_id', "")).first()

    book_id = kwargs.get('item_id')

    # create orderItem of the selected book
    order_item, status = OrderItem.objects.get_or_create(book=book, price_in_cart=book.price)

    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()

    books_for_order = OrderItem.objects.all().order_by('-book')
    sbooks = SaveItem.objects.all()

    context = {'user_order': user_order, 'books_for_order': books_for_order, 'sbooks': sbooks}

    # show confirmation message and redirect back to the same page
    messages.info(request, "Item has been added to cart")
    return redirect(reverse('book_details', args=(book_id,)))

@login_required()
def add_to_cart_from_saved(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)

    # filter books by id
    book = books.objects.filter(id=kwargs.get('item_id', "")).first()

    # create orderItem of the selected book
    saved_to_cart, status = OrderItem.objects.get_or_create(book_id=kwargs.get('item_id'))
    saved_to_cart.is_saved_for_later = False
    saved_to_cart.save()

    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(saved_to_cart)
    if status:
        # generate a reference code
        user_order.ref_code = generate_save_id()
        user_order.save()

    sbooks = SaveItem.objects.all()

    books_for_order = OrderItem.objects.exclude(is_saved_for_later=True).order_by('-book')

    context = {'user_order': user_order, 'books_for_order': books_for_order, 'sbooks': sbooks}
    return render(request,'shopping_cart/order_summary.html', context)

@login_required()
def add_to_saved(request, **kwargs):

    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)

    # filter books by id
    saved_book = books.objects.filter(id=kwargs.get('item_id', "")).first()

    # create orderItem of the selected book
    saved_item, status = SaveItem.objects.get_or_create(saved_book=saved_book)

    # create saved item that's associated with the user
    user_save, status = Saved.objects.get_or_create(owner=user_profile, is_saved_for_later=False)
    user_save.saved_items.add(saved_item)

    if status:
        # generate a reference code
        user_save.ref_code = generate_save_id()
        user_save.save()

    # show confirmation message and redirect back to the same page
    messages.info(request, "Item saved for later.")
    return redirect(reverse('products:product-list'))

@login_required()
def add_to_saved_from_cart(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)

    # filter books by id
    saved_book = books.objects.filter(id=kwargs.get('item_id', "")).first()

    # create saveItem of the selected book
    saved_item, status = SaveItem.objects.get_or_create(saved_book=saved_book)

    # create saved that's associated with the user
    user_save, status = Saved.objects.get_or_create(owner=user_profile, is_saved_for_later=True)
    user_save.saved_items.add(saved_item)

    sbooks = SaveItem.objects.all()

    cart_to_saved, status = OrderItem.objects.get_or_create(book_id=kwargs.get('item_id'))
    cart_to_saved.is_saved_for_later = True
    cart_to_saved.save()

    books_for_order = OrderItem.objects.exclude(is_saved_for_later=True).order_by('-book')

    if status:
        # generate a reference code
        user_save.ref_code = generate_save_id()
        user_save.save()

    context = {'sbooks': sbooks, 'books_for_order': books_for_order}
    return render(request,'shopping_cart/order_summary.html', context)

@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()

    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)

    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    sbooks = SaveItem.objects.all()
    books_for_order = OrderItem.objects.all()

    context = {'sbooks': sbooks, 'books_for_order': books_for_order, 'user_order': user_order}
    return render(request,'shopping_cart/order_summary.html', context)

@login_required()
def delete_from_saved(request, item_id):
    item_to_delete = SaveItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
    
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)

    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    sbooks = SaveItem.objects.all()
    books_for_order = OrderItem.objects.all()

    context = {'sbooks': sbooks, 'books_for_order': books_for_order, 'user_order': user_order}
    return render(request,'shopping_cart/order_summary.html', context)

@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)

    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    sbooks = SaveItem.objects.all()
    books_for_order = OrderItem.objects.all()

Bookstore/shopping_cart/templates/shopping_cart/order_summary.html
<!DOCTYPE html>
<html lang="en">
  
<head>
  <style>
    #myImg {
    border-radius: 5px;
    cursor: pointer;
    transition: 0.3s;
    }

    #myImg:hover {opacity: 0.7;}

    .modal {
    display: none; 
    position: fixed; 
    z-index: 1; 
    padding-top: 100px;
    left: 0;
    top: 0;
    width: 100%; 
    height: 100%; 
    overflow: auto; 
    background-color: rgb(0,0,0); 
    background-color: rgba(0,0,0,0.9); 
    }

    .modal-content {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 400px;
    }

    .close {
    position: absolute;
    top: 15px;
    right: 35px;
    font-size: 60px;
    font-weight: bold;
    }

    .close:hover,
    .close:focus {
    cursor: pointer;
    }
  </style>

  <meta charset="UTF-8">
  <title> Bookbuy </title>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
  
<body>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">G19 Bookstore </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarsExampleDefault">
            <ul class="navbar-nav m-auto">
                <li class="nav-item m-auto">
                    <a class="nav-link" href="{% url 'book_browsing:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Profile <span class="sr-only">(current)</span></a>
                </li>
            </ul>

            <form class="form-inline my-2 my-lg-0">   
                <a class="btn btn-success btn-sm ml-3" href="{%  url 'shopping_cart:order_summary' %}">
                    <i class="fa fa-shopping-cart"></i> Cart
                    <span class="badge badge-light"></span>
                </a>
            </form>
        </div>
    </div>
  </nav>

  <section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">YOUR CART</h1>
     </div>
  </section>
  {% include 'messages.html' %}
    {% block content %}
      {{ message }}
    {% endblock content %}
  <div class="container mb-4">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th scope="col"><strong>Book</strong></th>
                            <th scope="col"><strong>Quantity</strong></th>
                            <th scope="col" class="text-right"><strong>Price</strong></th>
                            <th scope="col"> </th>
                            <th scope="col"> </th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for book in books_for_order %}
                          <tr>
                            <td><img src="/static/images/product/{{ book.book.coverImage }} " class="rounded" style="width:50px;height:80px;" alt="{{book.name}}"></td>
                            <td><a href="/book/{{book.book.pk}}" style="color:black">'{{ book.book.name }}'</a></td>                    
                            <td>
                              <div class="input-group">
                                <span class="input-group-btn">
                                  <a class="btn btn-default btn-number" href="{% url 'shopping_cart:decrease_item_quantity' book.book_id %}">
                                    <span class="fa fa-minus-square" style="color:red;"></span>
                                  </a>
                                </span>
                                <p>{{book.quantity}}</p>
                                <span class="input-group-btn">
                                    <a class="btn btn-default btn-number" href="{% url 'shopping_cart:increase_item_quantity' book.book_id %}">
                                      <span class="fa fa-plus-square" style="color:green;"></span>
                                    </a> 
                                </span>
                              </div>
                            </td>
                            <td class="text-right" id="price">${{ book.price_in_cart }}</td>
                            <td class="text-right">
                              <button class="btn btn-sm btn-dark"> 
                                <a href="{% url 'shopping_cart:add_to_saved_from_cart' book.book_id %}" style="color:white">Save for later</a>
                              </button>
                            </td>
                            <td>
                              <button class="btn btn-sm btn-danger"> 
                                <a href="{% url 'shopping_cart:delete_item' book.id %}" style="color:white"
                                  onclick="return confirm_delete();">Remove 
                                </a>
                              </button>
                            </td>
                          </tr>
                        {% empty %}
                          <tr>
                            <td colspan= 6> Your cart is empty. </td>
                          </tr>
                        {% endfor %}

                        <tr>
                          {% if user_order.get_cart_total != None %}
                          <td></td>
                          <td></td>
                          <td><strong>Order Total:</strong></td>
                          <td class="text-right">$<strong>{{ user_order.get_cart_total }}</strong></td>
                          <td></td>
                          <td></td>
                          {% endif %}
                        </tr>
                        <tr>
                          <td colspan=3>
                            <a href="{% url 'book_browsing:home'  %}" class="btn-lg btn-warning pull-left">
                              {% if user_order %}Continue Shopping{% else %}Continue Shopping {% endif %}
                            </a> 
                          </td>
                          <td></td>
                          <td class="text-right">
                            {% if user_order.get_cart_items %}
                              <a href="{% url 'shopping_cart:checkout' %}" class="pull-right btn-lg btn-primary">Checkout</a>
                            {% endif %}
                          </td>
                          <td colspan=2></td>
                        </tr>
                      </tbody>
                </table>
            </div>
        </div>
    </div>
  </div>

  <div class="container mb-4">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">  
                  <thead>
                    <tr>
                        <th></th> 
                        <th></th> 
                        <th></th> 
                        <th></th> 
                        <th><strong>Saved for later</strong></th>
                        <th></th> 
                        <th></th> 
                        <th></th> 
                    </tr>
                  </thead>            
                  <thead>
                    <tr>
                        <th></th>
                        <th scope="col"><strong>Book</strong></th>
                        <th scope="col"></th> 
                        <th scope="col"></th> 
                        <th scope="col"></th> 
                        <th scope="col"><strong>Price</strong></th>
                        <th scope="col"></th>   
                        <th scope="col"></th> 
                    </tr>
                  </thead>
                  <tbody>
                    {% for book in sbooks %}
                      <tr>
                        <td><img src="{{ book.saved_book.coverImage.url }} " class="rounded" style="width:50px;height:80px;" alt="{{book.name}}"></td> 
                        <td><a href="/book/{{book.saved_book.pk}}" style="color:black">'{{ book.saved_book.name }}'</a></td> 
                        <td></td> 
                        <td></td>  
                        <td></td>         
                        <td id="price">${{ book.saved_book.price }}</td>
                        <td class="text-right"><button class="btn btn-sm btn-success"> 
                          <a href="{% url 'shopping_cart:add_to_cart_from_saved' book.saved_book.id %}" style="color:white">Add to cart</button>
                          </a>
                        </td>
                        <td><button class="btn btn-sm btn-danger"> 
                          <a href="{% url 'shopping_cart:delete_item_from_saved' book.id %}" style="color:white"
                            onclick="return confirm_delete_saved();">Remove</button>
                          </a>
                        </td>
                      </tr>
                    {% empty %}
                      <tr>
                        <td colspan= 7> Your don't have any saved items. </td>
                        <td></td> 
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>
  </div>

</body>

{% block scripts %}
  <script>
    function confirm_delete(){
      return confirm("Are you sure you want to remove this item from cart?");
    }  </script>

  <script>
    function confirm_save(){
      return confirm("Are you sure you want to save this item for later?");
    }  </script>
{% endblock scripts %}

Bookstore/shopping_cart/templates/shopping_cart/purchase_success.html
{% extends 'base.html' %}

{% block content %}
    <h1>Thank you for your purchase!</h1>
    <a href="{% url 'products:product-list' %}">Head back home</a>
{% endblock content %}

Bookstore/shopping_cart/templates/shopping_cart/ref_order_summary.html
{% extends "base.html" %}

{% block content %}

 <section>
   <div class="row">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>no.</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.books.name }}
            <span class="pull-right">
              <a href="{% url 'shopping_cart:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fas fa-trash"></i>
              </a>
            </span>
          </td>
          <td>{{ item.books.price }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=2>
          <strong class="pull-right">Order Total:</strong>
        </td>
        
        <td colspan= 1>
          $<strong>{{ order.get_cart_total }}</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="{% url 'products:product-list' %}" class="btn btn-warning pull-left">
            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a> 
        </td>
        <td colspan=2>
          {% if order.get_cart_items %}
            <a href="{% url 'shopping_cart:checkout' %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
          {% endif %}
        </td>
      </tr>
    </table>
     
   </div>
 </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %} 

Bookstore/shopping_cart/templates/shopping_cart/stripe_default_form.html
<script src="https://js.stripe.com/v3/"></script>

<form action="." method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="{{ STRIPE_PUBLISHABLE_KEY }}"
    data-amount="999"
    data-name="Justdjango"
    data-description="Example charge"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto">
  </script>
</form>