Bookstore/Bookstore/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from book_details import views
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', include('book_browsing.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^products/', include('products.urls', namespace='products')),
    url('profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^author/(\d+)/$', views.bookAuthorsView.as_view(), name='book_author'),
    path('book/<int:pk>', views.bookDetailsView.as_view(), name='book'),
    path('author/<int:pk>', views.bookAuthorsView.as_view(), name='book-author'),
    url(r'^book/(?P<pk>\d+)/$', views.bookDetailsView.as_view(), name='book_details')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bookstore/accounts/urls.py
from django.conf.urls import url

from .views import my_profile

app_name = 'accounts'

urlpatterns = [
	url(r'^profile/$', my_profile, name='profiles'),
]

Bookstore/book_browsing/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'book_browsing'

urlpatterns = [
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('book/', views.book, name='book'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('order/', views.order, name='order'),
    path('new-book/', views.newBook, name='new-book'),
    path('search/', views.search, name='search'),
    path('fantasy/', views.fantasy, name='fantasy'),
    path('romance/', views.romance, name='romance'),
    path('fiction/', views.fiction, name='fiction'),
    path('history/', views.history, name='history'),
    path('thriller/', views.thriller, name='thriller'),
    path('new-release/', views.newRelease, name='new-release'),
    path('top-sellers/', views.topSeller, name='top-sellers'),
    path('filter-data/', views.filterData, name='filter-data'),
    path('filter-released-data/', views.filterReleasedData, name='filter-released-data'),
    path('get-book-details/', views.getBookDetailsById, name='get-book-details'),
    path('ajax-submit/', views.ajaxSubmit, name='ajax-submit')
]

Bookstore/home/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage_view, name='the_homepage_base'),
    url(r'^home/$', views.homepage_view, name = 'the_homepage'),
]

Bookstore/shopping_cart/urls.py
from django import views
from django.conf.urls import url
from django.urls import path

from .views import (
    add_to_cart,
    add_to_cart_from_saved,
    add_to_cart_from_detail,
    increase_item_quantity,
    decrease_item_quantity,
    add_to_saved,
    add_to_saved_from_cart,
    delete_from_cart,
    delete_from_saved,
    order_details,
    checkout,
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^add-to-cart-from-saved/(?P<item_id>[-\w]+)/$', add_to_cart_from_saved, name="add_to_cart_from_saved"),
    url(r'^add-to-cart-from-detail/(?P<item_id>[-\w]+)$', add_to_cart_from_detail, name="add_to_cart_from_detail"),
    url(r'^increase_item_quantity/(?P<item_id>[-\w]+)/$', increase_item_quantity, name="increase_item_quantity"),
    url(r'^decrease_item_quantity/(?P<item_id>[-\w]+)/$', decrease_item_quantity, name="decrease_item_quantity"),
    url(r'^add-to-saved/(?P<item_id>[-\w]+)/$', add_to_saved, name="add_to_saved"),
    url(r'^add-to-saved_from_cart/(?P<item_id>[-\w]+)/$', add_to_saved_from_cart, name="add_to_saved_from_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^item/delete_saved/(?P<item_id>[-\w]+)/$', delete_from_saved, name='delete_item_from_saved'),
    url(r'^checkout/$', checkout, name='checkout'),
]

Bookstore/book_browsing/models.py
from tempfile import template

from shopping_cart.templatetags.cart_template_tag import register


@register.filter
def count_true(value):
    return value.filter(boolean_field=True).count()

Bookstore/book_browsing/views.py
import books as books

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.template import RequestContext

from accounts.models import Profile
from products.models import books
from shopping_cart.models import OrderItem, Order


def home(request):
    books_for_order = None
    user_order = None
    if request.user.is_active:
        user_profile = get_object_or_404(Profile, user=request.user)
        user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
        books_for_order = OrderItem.objects.all()[0:2]

    # Top Interest
    new_release = books.objects.order_by('releasedDate').reverse()[:15]
    on_sales = books.objects.all().order_by("name")[:15]
    feature_products = books.objects.filter(Q(category='Entertainment')).order_by("name")[:15]

    # Best Selling
    best_sellings = OrderItem.objects.all()

    # Book
    all_books = books.objects.all()

    # Science Fiction
    science_fiction_books = books.objects.filter(Q(genre="Science Fiction")).order_by('name')

    # History Book
    history_books = books.objects.filter(Q(genre="Science Fiction")).order_by('name')

    # Fantasy Book
    fantasy_books = books.objects.filter(Q(genre="Fantacy")).order_by('name')

    context = {'books_for_order': books_for_order, "user_order": user_order, "new_release": new_release, "on_sales": on_sales, "feature_products": feature_products, "best_sellings": best_sellings, "all_books": all_books, "science_fiction_books": science_fiction_books, "history_books": history_books, "fantasy_books": fantasy_books}
    return render(request, 'index.html', context)


def account(request):
    template = "account.html",
    return render(request, template)


def checkout(request):
    template = "checkout.html",
    return render(request, template)


def login(request):
    template = "login.html",
    return render(request, template)


def book(request):
    template = "book.html",
    return render(request, template)


def about(request):
    template = "about.html",
    return render(request, template)


def contact(request):
    template = "contact.html",
    return render(request, template)


def order(request):
    template = "order.html",
    return render(request, template)


def newBook(request):
    template = 'new_book.html',
    return render(request, template)


def cart(request):
    template = 'order_summary.html',
    return render(request, template)


def search(request):
    query = request.GET.get('q')
    bookResult = None
    results = None
    count = None
    try:
        query = str(query)
    except ValueError:
        query = None

    if query:
        results = books.objects.filter(Q(name=query) | Q(genre=query))
        count = results.count()

    if results:
        page = request.GET.get('page', 1)
        paginator = Paginator(results, 8)
        try:
            bookResult = paginator.page(page)
        except PageNotAnInteger:
            bookResult = paginator.page(1)
        except EmptyPage:
            bookResult = paginator.page(paginator.num_pages)

    return render(request, 'search.html', {"books": bookResult, "count": count})


def viewPage(request):
    queryString = request.path
    pageName = queryString.replace('/', '').title()

    if pageName == "Fiction":
        pageName = "Science Fiction"

    results = books.objects.filter(Q(genre=pageName)).order_by('name')
    page = request.GET.get('page', 1)
    paginator = Paginator(results, 8)
    try:
        bookResult = paginator.page(page)
    except PageNotAnInteger:
        bookResult = paginator.page(1)
    except EmptyPage:
        bookResult = paginator.page(paginator.num_pages)
    return render(request, 'book.html', {'books': bookResult, "title": pageName, "count": results.count()})


def fantasy(request):
    return viewPage(request)


def romance(request):
    return viewPage(request)


def fiction(request):
    return viewPage(request)


def history(request):
    return viewPage(request)


def thriller(request):
    return viewPage(request)


def newRelease(request):
    results = books.objects.order_by('releasedDate').reverse()[:10]
    page = request.GET.get('page', 1)
    paginator = Paginator(results, 8)
    try:
        bookResult = paginator.page(page)
    except PageNotAnInteger:
        bookResult = paginator.page(1)
    except EmptyPage:
        bookResult = paginator.page(paginator.num_pages)
    return render(request, 'new_release.html', {'books': bookResult, "title": "New Release", "count": results.count()})


def topSeller(request):
    template = 'top_sellers.html',
    return render(request, template)


def filterData(request):
    sortType = request.GET.get("sort_type")
    queryString = request.GET.get("page_url")

    pageName = queryString.replace('/', '').title()

    if pageName == "Fiction":
        pageName = "Science Fiction"

    if sortType == 'releasedDate':
        results = books.objects.filter(Q(genre=pageName)).order_by('releasedDate').reverse()
    elif sortType == 'price':
        results = books.objects.filter(Q(genre=pageName)).order_by('price').reverse()
    elif sortType == 'pricelowtohigh':
        results = books.objects.filter(Q(genre=pageName)).order_by('price')
    elif sortType == 'atoz':
        results = books.objects.filter(Q(genre=pageName)).order_by('name')
    else:
        results = books.objects.filter(Q(genre=pageName)).order_by(sortType)

    page = request.GET.get('page', 1)
    paginator = Paginator(results, 8)
    try:
        bookResult = paginator.page(page)
    except PageNotAnInteger:
        bookResult = paginator.page(1)
    except EmptyPage:
        bookResult = paginator.page(paginator.num_pages)

    return render(request, 'ajax/book.html', {'books': bookResult})


def filterReleasedData(request):
    sortType = request.GET.get("sort_type")
    if sortType == 'releasedDate':
        results = books.objects.all().order_by('releasedDate').reverse()
    elif sortType == 'price':
        results = books.objects.all().order_by('price', 'releasedDate').reverse()
    elif sortType == 'pricelowtohigh':
        results = books.objects.all().order_by('price', 'releasedDate')
    elif sortType == 'atoz':
        results = books.objects.all().order_by('name', 'releasedDate')
    else:
        results = books.objects.all().order_by(sortType, 'releasedDate')

    page = request.GET.get('page', 1)
    paginator = Paginator(results, 8)
    try:
        bookResult = paginator.page(page)
    except PageNotAnInteger:
        bookResult = paginator.page(1)
    except EmptyPage:
        bookResult = paginator.page(paginator.num_pages)

    return render(request, 'ajax/book.html', {'books': bookResult})


def getBookDetailsById(request):
    bookId = request.GET.get("book_id")
    bookObject = books.objects.get(pk=int(bookId))

    return render(request, 'ajax/book_details.html', {'book': bookObject})


def ajaxSubmit(request):
    print(request)
    return

Bookstore/book_browsing/templates/common/footer.html
<footer>
    <!-- footer-top-start -->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer-top-menu bb-2">
                        <nav>
                            <ul>
                                <li>
                                    <a href="{% url 'book_browsing:home' %}">home</a>
                                </li>
                                <li>
                                    <a href="{% url 'book_browsing:contact' %}">contact us</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- footer-top-start -->

    <!-- footer-mid-start -->
    <div class="footer-mid ptb-50">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-12">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-12">
                            <div class="single-footer br-2 xs-mb">
                                <div class="footer-title mb-20">
                                    <h3>Products</h3>
                                </div>
                                <div class="footer-mid-menu">
                                    <ul>
                                        <li>
                                            <a href="{% url 'book_browsing:about' %}">About us</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'book_browsing:new-book' %}">New Books</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-12">
                            <div class="single-footer br-2 xs-mb">
                                <div class="footer-title mb-20">
                                    <h3>Our Group</h3>
                                </div>
                                <div class="footer-mid-menu">
                                    <ul>
                                        <li>
                                            <a href="{% url 'book_browsing:contact' %}">Contact us</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)">Sitemap</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'accounts:profiles' %}">My account</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-12">
                            <div class="single-footer br-2 xs-mb">
                                <div class="footer-title mb-20">
                                    <h3>Your account</h3>
                                </div>
                                <div class="footer-mid-menu">
                                    <ul>
                                        <li>
                                            <a href="{% url 'book_browsing:contact' %}">Addresses</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'book_browsing:order' %}">Orders</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)">Personal info</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="single-footer mrg-sm">
                        <div class="footer-title mb-20">
                            <h3>STORE INFORMATION</h3>
                        </div>
                        <div class="footer-contact">
                            <p class="address">
                                <span>My Company</span>
                                33351, Florida, USA.
                            </p>
                            <p>
                                <span>Call us now:</span>
                                (+1)347-972-0000
                            </p>
                            <p>
                                <span>Email:</span>
                                support@group19.com
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- footer-mid-end -->

    <!-- footer-bottom-start -->
    <div class="footer-bottom">
        <div class="container">
            <div class="row bt-2">
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="copy-right-area">
                        <p>Copyright &copy; <a href="javascript:void(0)">Group 19 Online Book Store</a>. All Right Reserved.
                        </p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="payment-img text-right">
                        <a href="javascript:void(0)">
                            <img src="/static/images/1(3).png" alt="payment">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- footer-bottom-end -->
</footer>

Bookstore/book_browsing/templates/common/header.html
<header>
    <!-- header-top-area-start -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark header-mid-area">
        <div class="container">
            <a class="navbar-brand" href="{% url 'book_browsing:home' %}">G19 Bookstore </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div></div>

            <div class="row" style="position:absolute; right:1050px; top:0px;">
                <div class="header-search">
                    <form action="{% url 'book_browsing:search' %}" method="get">
                        <input type="text" name="q" placeholder="Search entire store here..." value="{{ query }}">
                        <button type="submit" class="search-btn"><i class='fa fa-search'></i></button>
                    </form>
                </div>
            </div>

            <div class="collapse navbar-collapse justify-content-end" id="navbarsExampleDefault">
                <ul class="navbar-nav m-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:profiles' %}">Profile <span class="sr-only">(current)</span></a>
                    </li>
                </ul>

                <div class="my-cart">
                    <ul>
                        <li><a href="javascript:void(0)"><i class="fa fa-shopping-cart"></i>Cart</a>
                            <span>{{ user_order.cart_item_count }}</span>
                            <div class="mini-cart-sub">
                                <div class="cart-product">
                                    {% for book in books_for_order %}
                                        <div class="single-cart">
                                            <div class="cart-img">
                                                <a href="javascript:void(0)"><img src="/static/images/product/{{ book.book.coverImage }}" alt="{{ book.book.name }}"></a>
                                            </div>
                                            <div class="cart-info">
                                                <h5><a href="javascript:void(0)">{{ book.book.name }}</a></h5>
                                                <p>{{ book.quantity }} x ${{ book.book.price }}</p>
                                            </div>
                                            <div class="cart-icon">
                                                <a href="{% url 'shopping_cart:delete_item_from_saved' book.id %}" onclick="return confirm_delete_saved();"><i class="fa fa-remove"></i></a>
                                            </div>
                                        </div>
                                    {% empty %}
                                        <h4>Your cart is empty</h4>
                                    {% endfor %}
                                </div>
                                <div class="cart-totals">
                                    <h5><span>{% if user_order.get_cart_total != None %} Total ${{ user_order.get_cart_total|floatformat:'2' }}{% endif %}</span></h5>
                                </div>
                                <div class="cart-bottom">
                                    <a class="view-cart" href="{% url 'shopping_cart:order_summary' %}">view cart</a>
                                    <a href="{% url 'shopping_cart:checkout' %}">Check out</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!-- header-top-area-end -->

    <!-- main-menu-area-start -->
    <div class="main-menu-area d-md-none d-none d-lg-block sticky-header-1" id="header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="menu-area">
                        <nav>
                            <ul>
                                <li class="active"><a href="{% url 'book_browsing:home' %}">Home<i class="fa fa-angle-down"></i></a>
                                    <div class="sub-menu">
                                        <ul>
                                            <li><a href="{% url 'book_browsing:about' %}">About Us</a></li>
                                            <li><a href="{% url 'book_browsing:contact' %}">Contact Us</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li><a href="javascript:void(0);">Book</a>
                                    <div class="sub-menu">
                                        <ul>
                                            <li><a href="{% url 'book_browsing:new-release' %}">New Release</a></li>
                                            <li><a href="{% url 'book_browsing:top-sellers' %}">Top Sellers</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li><a href="javascript:void(0)" class="book-list" id="book" data-target="productBook">Search by Genre</a>
                                    <div class="sub-menu">
                                        <ul>
                                            <li><a href="{% url 'book_browsing:fantasy' %}">Fantasy</a></li>
                                            <li><a href="{% url 'book_browsing:romance' %}">Romance</a></li>
                                            <li><a href="{% url 'book_browsing:fiction' %}">Science Fiction</a></li>
                                            <li><a href="{% url 'book_browsing:history' %}">History</a></li>
                                            <li><a href="{% url 'book_browsing:thriller' %}">Thriller</a></li>
                                        </ul>
                                    </div>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- main-menu-area-end -->

    <!-- mobile-menu-area-start -->
    <div class="mobile-menu-area d-lg-none d-block fix">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="mobile-menu">
                        <nav id="mobile-menu-active" style="display: block;">
                            <ul id="nav">
                                <li><a href="{% url 'book_browsing:home' %}">Home</a>
                                    <ul>
                                        <li><a href="{% url 'book_browsing:about' %}">About Us</a></li>
                                        <li><a href="{% url 'book_browsing:contact' %}">Contact Us</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'book_browsing:book' %}">Book</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- mobile-menu-area-end -->
</header>